baseurl = "/" # Controls base URL
languageCode = "en-US" # Controls html lang attribute
title = "Homicide in Chicago 1870-1930" # Homepage title and page title suffix
paginate = 5 # Number of posts to show before paginating
theme = "bulma" # to use as default theme

enableRobotsTXT = true # Suggested, it generates a robots.txt
googleAnalytics = "" # Optional, add tracking Id for analytics
disqusShortname = "" # Optional, add Disqus shortname for comments
SectionPagesMenu = "main" # Enable menu system for lazy bloggers

[params]
  theme_variant = "lux" # possible value for the theme_variant `cerulean,cosmo,cyborg,darkly,flatly,journal,litera,lumen,lux,materia,minty,pulse,sandstone,simplex,slate,solar,spacelab,superhero,united,yeti`
  description = "The history of homicide in Chicago, 1870-1930, based on over 11,0000 Chicago Police Department homicide reports." # Suggested, controls default description meta and landing page
  powered_by = "love" # Optional, controls name display on footer
  hide_author = false # Optional, set true to hide author name on posts
  images = [] # Suggested, controls default OpenGraph images controls author name display on meta tag
#  github  = "github" # Optional, to display link to github account in menu bar
#  twitter = "twitter" # Optional, to display link to twitter account in menu bar

SectionPagesMenu = "main"

[permalinks]
  posts = "/:section/:filename/"

[[menu.main]]
  name = "Database"
  weight = 1
    identifier = "database"
  url = "/search/"

[[menu.main]]
  name = "History"
  weight = 2
    identifier = "historical"
  url = "/historical/movements/working/"

[[menu.main]]
  name = "Timeline"
  weight = 3
    identifier = "timeline"
  url = "/historical/timeline"

[[menu.main]]
  name = "Law"
  weight = 4
    identifier = "legal"
  url = "/legal/cpd/"

[[menu.main]]
  name = "Crime"
  weight = 5
    identifier = "crimes"
  url = "/crimes/"

[[menu.main]]
  name = "Publications"
  weight = 6
    identifier = "pubs"
  url = "/pubs/"

[[menu.main]]
  name = "Interviews"
  weight = 7
    identifier = "gallery"
  url = "/gallery/bienen/"

[[menu.main]]
  name = "About"
  weight = 8
    identifier = "about"
  url = "/about/"

[outputs]
  home = ["HTML", "JSON"]
